name: BuildUSD MacOS

on:
  push:
    branches:
      - testCommon
      - dev
      - release
  issue_comment:                                     
    types: [created]

jobs:
  MacOS:
    uses: ./.github/workflows/buildusd_common.yml
    with:
      artifact_name: usd-linux
      os: macos-13
      python_version: 3.11
      install_dependencies: |
        export PATH=/Applications/CMake.app/Contents/bin:$PATH
        sudo xcode-select -s /Applications/Xcode_14.1.app/Contents/Developer
        # Set SYSTEM_VERSION_COMPAT while installing Python packages to
        # accommodate the macOS version numbering change from 10.x to 11
        export SYSTEM_VERSION_COMPAT=1
        pip install PySide6 PyOpenGL setuptools
        export -n SYSTEM_VERSION_COMPAT
      build_usd: |
        export PATH=/Applications/CMake.app/Contents/bin:$PATH
        python3 build_scripts/build_usd.py --no-materialx --generator Xcode --build USDgen/build --src USDgen/src USDinst -v
