name: BuildUSD Linux

on:
  push:
    branches:
      - testCommon
      - dev
      - release
  issue_comment:                                     
    types: [created]

jobs:
  Linux:
    uses: ./.github/workflows/buildusd_common.yml
    with:
      artifact_name: usd-linux
      os: ubuntu-20.04
      python_version: 3.9
      install_dependencies: |
        sudo apt-get -qq update
        sudo apt-get install -y python3-setuptools libglew-dev libxrandr-dev libxcursor-dev libxinerama-dev libxi-dev
        pip install --upgrade pip
        pip install PySide2 PyOpenGL
      build_usd: |
        python3 build_scripts/build_usd.py --no-materialx --build USDgen/build --src USDgen/src USDinst -v

