name: BuildUSD Windows

on:
  push:
    branches:
      - testCommon
      - dev
      - release
  issue_comment:                                     
    types: [created]

jobs:
  Windows:
    uses: ./.github/workflows/buildusd_common.yml
    with:
      artifact_name: usd-win64
      os: windows-2019
      python_version: 3.9
      install_dependencies: |
        python -m pip install --upgrade pip
        python -m pip install PyOpenGL PySide2
      build_usd: |
        python build_scripts/build_usd.py --no-materialx --generator "Visual Studio 16 2019" --build USDgen/build --src USDgen/src USDinst --build-args USD,"-DPXR_ENABLE_PRECOMPILED_HEADERS=OFF" -v
